apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: erp-core-web
  namespace: bateriaexpert
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: erp-core-web
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: erp-core-queue
  namespace: bateriaexpert
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: erp-core-queue
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-001-fiscal-api
  namespace: bateriaexpert
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-001-fiscal-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-002-banking-api
  namespace: bateriaexpert
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-002-banking-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-003-notification-api
  namespace: bateriaexpert
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-003-notification-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-004-openfinance-api
  namespace: bateriaexpert
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-004-openfinance-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-005-geocoding-api
  namespace: bateriaexpert
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-005-geocoding-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
