apiVersion: v1
kind: Secret
metadata:
  name: erp-core-secrets
  namespace: bateriaexpert
  labels:
    app.kubernetes.io/name: erp-core-web
    app.kubernetes.io/part-of: bateriaexpert
type: Opaque
stringData:
  APP_KEY: base64:change-me
  DB_CENTRAL_PASSWORD: change-me
  REDIS_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: ms-001-secrets
  namespace: bateriaexpert
  labels:
    app.kubernetes.io/name: ms-001-fiscal-api
    app.kubernetes.io/part-of: bateriaexpert
type: Opaque
stringData:
  DB_PASSWORD: change-me
  REDIS_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: ms-002-secrets
  namespace: bateriaexpert
  labels:
    app.kubernetes.io/name: ms-002-banking-api
    app.kubernetes.io/part-of: bateriaexpert
type: Opaque
stringData:
  DB_PASSWORD: change-me
  REDIS_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: ms-003-secrets
  namespace: bateriaexpert
  labels:
    app.kubernetes.io/name: ms-003-notification-api
    app.kubernetes.io/part-of: bateriaexpert
type: Opaque
stringData:
  DB_PASSWORD: change-me
  REDIS_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: ms-004-secrets
  namespace: bateriaexpert
  labels:
    app.kubernetes.io/name: ms-004-openfinance-api
    app.kubernetes.io/part-of: bateriaexpert
type: Opaque
stringData:
  DB_PASSWORD: change-me
  REDIS_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: ms-005-secrets
  namespace: bateriaexpert
  labels:
    app.kubernetes.io/name: ms-005-geocoding-api
    app.kubernetes.io/part-of: bateriaexpert
type: Opaque
stringData:
  DB_PASSWORD: change-me
  REDIS_PASSWORD: ""
